INTYGFV-15007: Implementation of question Grund for medicinskt underlag.
sklintyg/common pull request #626
Opened 2022-11-29 17:01 UTC by ChrilleSigerhed

2022-11-29 19:41 UTC, IamFriberg commented on fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionUnderlag.java
> +            .typeId(UNDERLAG_SVAR_JSON_ID_4 + "[" + id + "].typ")
Should we refactor this to make it more clear to why we set typeId here and below we also use a different typeId as a type?

2022-11-30 08:42 UTC, mww-sopra-steria requested changes
A few things concerning the model that we need to revisit before we can complete this.

2022-11-30 08:42 UTC, mww-sopra-steria commented on fk/fk-parent/src/main/java/se/inera/intyg/common/fkparent/model/converter/RespConstants.java
> +    public static final String UNDERLAG_QUESTION_ID_0 = "4.1.0";
Are these needed? UNDERLAG_QUESTION_ID_0, UNDERLAG_QUESTION_ID_1, UNDERLAG_QUESTION_ID_2.

2022-11-30 08:42 UTC, mww-sopra-steria commented on support/src/main/java/se/inera/intyg/common/support/facade/model/config/CertificateDataConfigMedicalInvestigation.java
> +    List<CodeItem> typeOptions;
Already commented.. but this should probably be part of MedicalInvestigation.

2022-11-30 08:42 UTC, mww-sopra-steria commented on support/src/main/java/se/inera/intyg/common/support/facade/model/value/CertificateDataValueMedicalInvestigation.java
> +public class CertificateDataValueMedicalInvestigation {
This should consist of DateValue, CodeValue and TextValue.

2022-11-30 08:42 UTC, mww-sopra-steria commented on fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionUnderlag.java
> +    private static CertificateDataValueMedicalInvestigation getMedicalInvestigationValue(List<Underlag> underlag, int id) {
See comment on CertificateDataValueMedicalInvestigation. This complex type should consist of DateValue, CodeValue and TextValue.

2022-11-30 10:21 UTC, IamFriberg commented on fk/fk-parent/src/main/java/se/inera/intyg/common/fkparent/model/converter/RespConstants.java
> +    public static final String UNDERLAG_QUESTION_ID_0 = "4.1.0";
These have been removed.

2022-11-30 10:53 UTC, IamFriberg commented on fk/fk-parent/src/main/java/se/inera/intyg/common/fkparent/model/internal/Underlag.java
> +        public static UnderlagsTyp fromValue(String id) {
Removed

2022-12-02 10:34 UTC, mww-sopra-steria requested changes
Nice work! Just a small thing regarding the "withCitation" that would be great if you look at.

2022-12-02 14:51 UTC, ChrilleSigerhed commented on fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionUnderlag.java
> +                            multipleAndExpressionWithCitation(UNDERLAG_SVAR_JSON_ID_4 + "[0].typ", UNDERLAG_SVAR_JSON_ID_4 + "[0].datum",
Good suggestion, done!

2022-12-02 14:51 UTC, ChrilleSigerhed commented on support/src/main/java/se/inera/intyg/common/support/facade/util/ValidationExpressionToolkit.java
> +    public static String multipleAndExpressionWithCitation(String... expression) {
I agree.

2022-12-05 06:16 UTC, mww-sopra-steria approved these changes
Looks good! Approved!

2022-12-05 14:35 UTC, merged