INTYGFV-15077: Implementation of categories Hörsel och balanssinne -> Demens och andra kognitiva störningar
sklintyg/common pull request #662
Opened 2022-12-16 16:28 UTC by ChrilleSigerhed

Still under (WIP)

Tho I feel that this feature is has been growing out of proporsion, therefore I create this PR to give people the chance to partially look throught it. I hope this will mitigate the workload of reviewing this PR in the future.,

2022-12-19 09:39 UTC, mww-sopra-steria requested changes
Nice! I added a few comments based on our discussions. (Maybe some have already been fixed before I submitted this review :-) )

2022-12-19 09:39 UTC, mww-sopra-steria commented on ts/ts-bas/src/test/java/se/inera/intyg/common/ts_bas/v7/model/converter/certificate/question/QuestionBeskrivningRiskfaktorerTest.java
> +        class IncludeInternalBooleanValueTest extends InternalTextValueTest {
Rename class :-)

2022-12-19 12:41 UTC, ChrilleSigerhed commented on ts/ts-bas/src/test/java/se/inera/intyg/common/ts_bas/v7/model/converter/certificate/question/QuestionBeskrivningRiskfaktorerTest.java
> +        class IncludeInternalBooleanValueTest extends InternalTextValueTest {
Done!

2022-12-19 12:41 UTC, ChrilleSigerhed commented on support/src/testFixtures/java/se/inera/intyg/common/support/facade/testsetup/model/value/InternalValuePairTest.java
> +public abstract class InternalValuePairTest<T, S> {
Done!

2022-12-19 12:41 UTC, ChrilleSigerhed commented on support/src/testFixtures/java/se/inera/intyg/common/support/facade/testsetup/model/config/ConfigRadioBooleanMultipleCodeTest.java
> +        for (RadioMultipleCode radioMultipleCode : getExpectedRadioMultipleCodes()) {
Done!

2022-12-19 12:41 UTC, ChrilleSigerhed commented on support/src/testFixtures/java/se/inera/intyg/common/support/facade/testsetup/model/config/ConfigCheckboxMultipleCodeTest.java
> +        for (CheckboxMultipleCode checkboxMultipleCode : getExpectedListOfCodes()) {
Done!

2022-12-19 12:41 UTC, ChrilleSigerhed commented on support/src/main/java/se/inera/intyg/common/support/facade/model/config/Layout.java
> +    ROWS, COLUMNS, COLUMN, INLINE
Yes!

2022-12-20 06:49 UTC, mww-sopra-steria approved these changes
Great job! Approved!

2022-12-20 06:54 UTC, merged