INTYGFV-15291: Refactored FK7804 & AG7804.
sklintyg/common pull request #736
Opened 2023-02-21 10:14 UTC by ChrilleSigerhed

Removed duplicate code and broke out tests & creation of certificates into separate classes.

2023-02-21 14:00 UTC, mhornfeldt requested changes

2023-02-21 14:38 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/category/CategoryAtgarder.java
> +                        .expression(exists(AVSTANGNING_SMITTSKYDD_SVAR_JSON_ID_27))
Forgot to change it for the categories in lisjp. Will correct it.

2023-02-21 14:41 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/category/CategoryBedomning.java
> +                new CertificateDataValidation[]{}
I kept it since there was a test that asserted that category had an empty validation array. I will go ahead and remove it and update the test.

2023-02-21 14:46 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/category/CategoryGrundForMU.java
> +                        .expression(exists(AVSTANGNING_SMITTSKYDD_SVAR_JSON_ID_27))
fixed

2023-02-21 14:46 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/category/CategoryKontakt.java
> +                        .expression(exists(AVSTANGNING_SMITTSKYDD_SVAR_JSON_ID_27))
fixed

2023-02-21 14:46 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/category/CategoryMedicinskaBehandlingar.java
> +                        .build()
fixed

2023-02-21 14:46 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/category/CategorySysselsattning.java
> +                        .expression(exists(AVSTANGNING_SMITTSKYDD_SVAR_JSON_ID_27))
fixed

2023-02-21 15:20 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/question/QuestionAtgarder.java
> +                .id(ArbetslivsinriktadeAtgarderVal.INTE_AKTUELLT.getId())
Good suggestion, I like it!

2023-02-21 15:32 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/question/QuestionAtgarderBeskrivning.java
> +            ArbetslivsinriktadeAtgarderVal.ARBETSTRANING.getId(),
I get your point, but even tho this generates alot of code, I think it reads really well to print it out plain like this.

There is also a issue that ArbetslivsinriktadeAtgarderVal is not a shared model, FK7804 & AG7804 both have theire own model.

2023-02-21 15:47 UTC, ChrilleSigerhed commented on fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/question/QuestionMotiveringTidigtStartdatum.java
> +                                wrapWithParenthesis(
Done.

2023-02-21 15:48 UTC, ChrilleSigerhed commented on skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/model/converter/certificate/category/CategoryBedomning.java
> +                new CertificateDataValidation[]{}
No, I will go ahead and remove it and update the tests.

2023-02-21 15:56 UTC, mhornfeldt commented on skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/model/converter/certificate/question/QuestionAtgarder.java
> +            ArbetslivsinriktadeAtgarderVal.ARBETSTRANING.getId(),
I thought they were the same but then we skip it :)

2023-02-21 15:58 UTC, ChrilleSigerhed commented on skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/model/converter/certificate/question/QuestionDiagnosOnskasFormedlas.java
> +                        .expression(multipleOrExpression(exists(YES_ID), exists(NO_ID), not(exists(YES_ID)), not(exists(NO_ID))))
Done, changed it to:
``` .expression(withCitation("1"))```

2023-02-21 16:20 UTC, ChrilleSigerhed commented on skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/model/converter/certificate/question/QuestionDiagnosOnskasFormedlas.java
> +                        .expression(multipleOrExpression(exists(YES_ID), exists(NO_ID), not(exists(YES_ID)), not(exists(NO_ID))))
```.expression("1")```

2023-02-22 08:41 UTC, ChrilleSigerhed commented
Manually tested the changes and everything works as expected.

2023-02-22 08:53 UTC, mhornfeldt approved these changes

2023-02-22 09:17 UTC, merged